[tool.poetry]
name = "ai-chat-neural"
version = "0.1.0"
description = "Консольный ИИ-чат-бот с историей, логированием и тестами"
authors = ["TikhonovAS <tihas987@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.14"
python-dotenv = "^1.2.2"
requests = "^2.34.2"
# logging — это встроенный модуль, его не нужно указывать!

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0,<10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"